name: Validate

on:
  pull_request:
  workflow_dispatch:  

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Cache yarn 3
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        shell: bash
        run: yarn install
      - name: Lint
        shell: bash
        run: yarn lint
      - name: Run Tests
        shell: bash
        run: yarn test:ci
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: test-results/junit*.xml
          reporter: jest-junit