name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Cache yarn 3
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        shell: bash
        run: yarn install
      - name: Build Library
        shell: bash
        run: yarn build
      - name: Quick version
        shell: bash
        run: npm version --git-tag-version false ${{github.ref_name}}
      - name: Publish package
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
