name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        shell: bash
        run: yarn install
      - name: Build Library
        shell: bash
        run: yarn build
      - name: Publish package
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
